### ISSUE TITLE
Cannot adjust font size

### ISSUE THREAD

**Issue by sharpfoxdev** [JorgEdmundo/cybertron-shifted#1]
I'm in love with the theme and the color scheme, very nicely readable. But I noticed I cannot change the font size using ctrl+scroll. Changing the font size in the appearance settings also doesn't work, the only way to increase the font size is to change zoom level in the settings. I am using Obsidian version v1.3.5.

**Comment by JorgEdmundo** [comment]
@sharpfoxdev thank you for using the theme and for commenting on the issue. I've created a fix. Hope that is now working fine for you.
I am open to further feedback.
Thank you!

**Comment by JorgEdmundo** [comment]
A fix has been submitted to change the font size from the Settings->Appearance.
